# Generated by Django 3.2.12 on 2022-11-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_checklisttaskitem_options'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='jobtitle',
        ),
        migrations.AddField(
            model_name='customuser',
            name='JT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.jobtitle'),
        ),
    ]
