# Generated by Django 4.1.3 on 2022-11-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_checklisttaskitem_time_control_and_more'),
        ('users', '0002_auto_20221123_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='JT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.jobtitle', verbose_name='Должность: '),
        ),
    ]
