# Generated by Django 4.1.3 on 2023-02-08 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_ei_nomen_payment_receiver_review_source_zakazremark_and_more'),
        ('users', '0003_alter_customuser_jt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='OBJ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект производства'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='TEL',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='TELEGRAMID',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='JT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.jobtitle', verbose_name='Должность'),
        ),
    ]
