# Generated by Django 4.1.3 on 2023-02-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_sotr_active_alter_zakazremark_date_and_more'),
        ('users', '0004_customuser_obj_customuser_tel_customuser_telegramid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='A_Tabel',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ввод табеля'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='A_TabelAdmin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ввод табеля Админ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='A_TabelReport',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отчет по табелю'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='A_TabelReportAdmin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отчет по табелю Админ'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='POD',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.podrazd', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='TEL',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='TELEGRAMID',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Telegram ID'),
        ),
    ]
