# Generated by Django 4.1.4 on 2023-03-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_sotr_active_alter_zakazremark_date_and_more'),
        ('users', '0005_customuser_a_tabel_customuser_a_tabeladmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sotr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.sotr', verbose_name='Сотрудник'),
        ),
    ]
