# Generated by Django 4.1.4 on 2023-03-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_sotr'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='A_Den',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ввод рабочего дня'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='A_DenReport',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Отчет по рабочим дням'),
        ),
    ]
