# Generated by Django 4.2.13 on 2024-10-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_a_den_customuser_a_denreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='A_Graphic',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ведение графика'),
        ),
    ]
