# Generated by Django 4.1.3 on 2022-11-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование чек-листа')),
            ],
            options={
                'verbose_name': 'Чек-лист сотрудника',
                'verbose_name_plural': 'Чек-листы сотрудников',
            },
        ),
    ]
