# Generated by Django 4.1.3 on 2022-11-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_taskjobtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskjobtitle',
            name='jobtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='jobtitlename',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Название должности'),
        ),
    ]
