# Generated by Django 4.1.3 on 2022-11-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_taskjobtitle_jobtitle_alter_jobtitle_jobtitlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskjobtitle',
            name='Tasks',
            field=models.ManyToManyField(to='catalog.task'),
        ),
        migrations.AlterField(
            model_name='taskjobtitle',
            name='jobtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.jobtitle', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='ChekListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField(blank=True, null=True)),
                ('ChekList', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.taskjobtitle')),
                ('Tasks', models.ManyToManyField(to='catalog.task')),
            ],
        ),
    ]
