# Generated by Django 4.1.3 on 2022-11-19 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_task_taskname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskjobtitle',
            name='Tasks',
        ),
        migrations.AlterField(
            model_name='taskjobtitle',
            name='jobtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.jobtitle', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='TS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Задача на выполнение:')),
                ('order', models.IntegerField(verbose_name=3)),
                ('cheklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.taskjobtitle', verbose_name='Задача на выполнение')),
            ],
            options={
                'verbose_name': 'Задача на выполнение',
                'verbose_name_plural': 'Перечень задач',
            },
        ),
    ]
