# Generated by Django 4.1.3 on 2022-11-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_taskjobtitle_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Задача на выполнение:')),
                ('order', models.IntegerField(verbose_name=3)),
                ('cheklistlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.taskjobtitle')),
                ('tasklink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.task')),
            ],
            options={
                'verbose_name': 'Задача на выполнение',
                'verbose_name_plural': 'Перечень задач',
            },
        ),
        migrations.DeleteModel(
            name='TS',
        ),
    ]
