# Generated by Django 4.1.3 on 2022-11-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_checklisttaskitem_delete_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttaskitem',
            name='name',
        ),
        migrations.AlterField(
            model_name='checklisttaskitem',
            name='order',
            field=models.IntegerField(verbose_name='Порядок'),
        ),
    ]
