# Generated by Django 4.1.3 on 2022-11-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_checklisttaskitem_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttaskitem',
            options={},
        ),
    ]
