# Generated by Django 4.1.3 on 2022-11-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_checklisttaskitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttaskitem',
            name='time_control',
            field=models.TimeField(null=True, verbose_name='time_control'),
        ),
        migrations.AlterField(
            model_name='checklisttaskitem',
            name='cheklistlink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.taskjobtitle', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='checklisttaskitem',
            name='tasklink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.task', verbose_name='Задача'),
        ),
    ]
