# Generated by Django 4.1.3 on 2022-11-26 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_checklisttaskitem_time_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttaskitem',
            name='time_control',
            field=models.TimeField(null=True, verbose_name='Время контроля'),
        ),
        migrations.CreateModel(
            name='TaskExe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time_control', models.TimeField()),
                ('order', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('time_exe', models.TimeField()),
                ('jobtitlelink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.jobtitle', verbose_name='Должность')),
                ('tasklink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.task', verbose_name='Задача')),
            ],
        ),
    ]
