# Generated by Django 4.1.3 on 2022-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_checklisttaskitem_time_control_taskexe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexe',
            options={'verbose_name': ' Задача на выполнение', 'verbose_name_plural': ' Задачи на выполнение'},
        ),
        migrations.AlterField(
            model_name='taskexe',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskexe',
            name='time_control',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskexe',
            name='time_exe',
            field=models.TimeField(null=True),
        ),
    ]
