# Generated by Django 4.1.3 on 2022-11-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_taskexe_options_alter_taskexe_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexe',
            name='taskjobtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.taskjobtitle', verbose_name='Должность'),
        ),
    ]
