# Generated by Django 4.1.3 on 2022-11-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_taskexe_taskjobtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexe',
            name='taskjobtitle',
        ),
        migrations.AddField(
            model_name='taskexe',
            name='taskjobtitlelink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.taskjobtitle', verbose_name='Чек-лист'),
        ),
    ]
