# Generated by Django 3.2.12 on 2022-11-29 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_taskexe_taskjobtitle_taskexe_taskjobtitlelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexe',
            name='user_exe',
            field=models.CharField(default='', max_length=60, null=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='checklisttaskitem',
            name='cheklistlink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.taskjobtitle', verbose_name='Чек-лист'),
        ),
    ]
