# Generated by Django 4.1.3 on 2022-12-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_taskexe_time_exe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexe',
            name='time_exe',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время исполнения'),
        ),
    ]
