# Generated by Django 4.1.3 on 2023-02-08 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_taskexe_time_exe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Nomen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Номенклатура')),
                ('img', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='static/IMG', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='Порядок')),
                ('cost', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('opisanie', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Описание')),
                ('ei', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ei', verbose_name='Ед.')),
            ],
            options={
                'verbose_name': 'Номенклатуру',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('summa', models.FloatField(null=True, verbose_name='Сумма')),
                ('zakaz_date', models.DateField(null=True, verbose_name='Дата заказа')),
                ('zakaz_number', models.CharField(default='', max_length=30, null=True, verbose_name='Номер заказа')),
                ('zakaz_content', models.CharField(default='', max_length=200, null=True, verbose_name='Содержание заказа')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Оплата по QR коду',
                'verbose_name_plural': 'Платежи по QR кодам',
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование объекта')),
            ],
            options={
                'verbose_name': 'Наименование объекта',
                'verbose_name_plural': 'Наименование объектов',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('text', models.TextField(default='', max_length=300, null=True, verbose_name='Содержание отзыва')),
                ('status', models.BooleanField(default=False)),
                ('user_exe', models.CharField(default='', max_length=30, null=True, verbose_name='Пользователь')),
                ('time_exe', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время отработки')),
                ('maker', models.CharField(default='', max_length=60, null=True, verbose_name='Создатель')),
                ('maker_tel', models.CharField(default='', max_length=30, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Место закупа')),
            ],
            options={
                'verbose_name': 'Место закупа',
                'verbose_name_plural': 'Места закупа',
            },
        ),
        migrations.CreateModel(
            name='Zakazremark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('remark', models.CharField(max_length=200, verbose_name='Комментартий')),
                ('creator', models.CharField(default='', max_length=30, null=True, verbose_name='Пользователь')),
                ('time_create', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время создания')),
                ('maker', models.CharField(default='', max_length=30, null=True, verbose_name='Пользователь')),
                ('time_make', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время выполнения')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Коментарий к заявке',
                'verbose_name_plural': 'Комментарии к заявке',
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('kol', models.FloatField(default=0, null=True, verbose_name='Количество')),
                ('cost', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('creator', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Создатель')),
                ('time_create', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время создания')),
                ('maker', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Исполнитель')),
                ('time_make', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время выполнения')),
                ('deliver', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Доставил')),
                ('time_deliv', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время доставления')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('ei_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ei', verbose_name='Ед.')),
                ('nomen_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nomen', verbose_name='Номенклатура')),
                ('receiver_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект')),
                ('source_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='База/Магазин')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
            },
        ),
        migrations.AddField(
            model_name='nomen',
            name='source_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='Место закупа'),
        ),
    ]
