# Generated by Django 4.1.4 on 2023-03-06 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_sotr_active_alter_zakazremark_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='den',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='den',
            name='vsert',
            field=models.FloatField(default=0, null=True, verbose_name='Выручка Предс.'),
        ),
    ]
