# Generated by Django 4.1.4 on 2023-03-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_den_obj_den_vsert'),
    ]

    operations = [
        migrations.AddField(
            model_name='den',
            name='kolblud',
            field=models.FloatField(default=0, null=True, verbose_name='Кол.блюд'),
        ),
        migrations.AddField(
            model_name='den',
            name='masblud',
            field=models.FloatField(default=0, null=True, verbose_name='Масса блюд'),
        ),
    ]
