# Generated by Django 4.1.4 on 2023-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_den_kolblud_den_masblud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabel',
            name='t1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='t Приход'),
        ),
        migrations.AddField(
            model_name='tabel',
            name='t2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='t Уход'),
        ),
    ]
