# Generated by Django 4.2.13 on 2024-09-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_causelist_menulist_position_alter_den_vsert_stoplist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Наименование чек-листа')),
                ('t1', models.TimeField(blank=True, null=True, verbose_name='t Начало')),
                ('t2', models.TimeField(blank=True, null=True, verbose_name='t Конец')),
                ('u1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Участок 1')),
                ('u2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Участок 2')),
                ('u3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Участок 3')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.podrazd', verbose_name='Подразделение')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Чек лист',
                'verbose_name_plural': 'Чек листы',
            },
        ),
        migrations.CreateModel(
            name='ChListRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование записи чек-листа')),
                ('t1', models.TimeField(blank=True, null=True, verbose_name='t Начало')),
                ('t2', models.TimeField(blank=True, null=True, verbose_name='t Конец')),
                ('ct1', models.TimeField(blank=True, null=True, verbose_name='t Начало')),
                ('ct2', models.TimeField(blank=True, null=True, verbose_name='t Конец')),
                ('chl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.chlist', verbose_name='Чек-лист')),
            ],
            options={
                'verbose_name': 'Чек лист (запись)',
                'verbose_name_plural': 'Чек лист (записи)',
            },
        ),
        migrations.CreateModel(
            name='ChListTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('created', models.TimeField(auto_now=True, null=True)),
                ('f1', models.BooleanField(blank=True, default=False, null=True, verbose_name='f1')),
                ('t1', models.DateTimeField(blank=True, null=True, verbose_name='t1')),
                ('f2', models.BooleanField(blank=True, default=False, null=True, verbose_name='f2')),
                ('t2', models.DateTimeField(blank=True, null=True, verbose_name='t2')),
                ('f3', models.BooleanField(blank=True, default=False, null=True, verbose_name='f3')),
                ('t3', models.DateTimeField(blank=True, null=True, verbose_name='t3')),
                ('cf1', models.BooleanField(blank=True, default=False, null=True, verbose_name='f1')),
                ('ct1', models.DateTimeField(blank=True, null=True, verbose_name='t1')),
                ('cf2', models.BooleanField(blank=True, default=False, null=True, verbose_name='f2')),
                ('ct2', models.DateTimeField(blank=True, null=True, verbose_name='t2')),
                ('cf3', models.BooleanField(blank=True, default=False, null=True, verbose_name='f3')),
                ('ct3', models.DateTimeField(blank=True, null=True, verbose_name='t3')),
                ('cst1', models.BooleanField(blank=True, default=True, null=True, verbose_name='cst1')),
                ('cst2', models.BooleanField(blank=True, default=True, null=True, verbose_name='cst2')),
                ('cst3', models.BooleanField(blank=True, default=True, null=True, verbose_name='cst3')),
                ('rem1', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Remark по работе uch1')),
                ('rem2', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Remark по работе uch2')),
                ('rem3', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Remark по работе uch3')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_author', to='catalog.sotr', verbose_name='Автор')),
                ('chl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.chlist', verbose_name='Чек-лист')),
                ('chlrec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChList_Record', to='catalog.chlistrec', verbose_name='Чек-лист-запись')),
                ('cs1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1_author', to='catalog.sotr')),
                ('cs2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs2_author', to='catalog.sotr')),
                ('cs3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs3_author', to='catalog.sotr')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.podrazd', verbose_name='Подразделение')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект')),
                ('s1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s1_author', to='catalog.sotr')),
                ('s2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s2_author', to='catalog.sotr')),
                ('s3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3_author', to='catalog.sotr')),
            ],
            options={
                'verbose_name': 'Запись в чек листе',
                'verbose_name_plural': 'Записи в чек листах',
            },
        ),
    ]
