# Generated by Django 4.2.13 on 2024-09-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_chlist_chlistrec_chlisttask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chlisttask',
            name='cf1',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='cf1'),
        ),
        migrations.AlterField(
            model_name='chlisttask',
            name='cf2',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='cf2'),
        ),
        migrations.AlterField(
            model_name='chlisttask',
            name='cf3',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='cf3'),
        ),
        migrations.AlterField(
            model_name='chlisttask',
            name='ct1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ct1'),
        ),
        migrations.AlterField(
            model_name='chlisttask',
            name='ct2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ct2'),
        ),
        migrations.AlterField(
            model_name='chlisttask',
            name='ct3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ct3'),
        ),
    ]
