# Generated by Django 4.2.13 on 2024-10-12 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_chlisttask_cf1_alter_chlisttask_cf2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadTaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unumber', models.IntegerField(blank=True, default=None, null=True, verbose_name='UNumber')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/photo/%Y-%m-%d/', verbose_name='Image')),
                ('taskpk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.chlisttask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Изображения задач',
            },
        ),
    ]
