# Generated by Django 4.2.13 on 2024-10-27 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_uploadtaskimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenHim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Номенклатура')),
                ('img', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='static/IMG', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='Порядок')),
                ('cost', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('opisanie', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Описание')),
                ('ei', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ei', verbose_name='Ед.')),
                ('source_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='Место закупа')),
            ],
            options={
                'verbose_name': 'Химия',
                'verbose_name_plural': 'Химия',
            },
        ),
        migrations.CreateModel(
            name='ZakazremarkHim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('remark', models.CharField(max_length=200, verbose_name='Комментарий')),
                ('creator', models.CharField(default='', max_length=30, null=True, verbose_name='Пользователь')),
                ('time_create', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время создания')),
                ('maker', models.CharField(default='', max_length=30, null=True, verbose_name='Пользователь')),
                ('time_make', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время выполнения')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Коментарий к заявке на химию',
                'verbose_name_plural': 'Комментарии к заявке на химию',
            },
        ),
        migrations.AlterField(
            model_name='graphic',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='datecreated',
            field=models.DateTimeField(null=True, verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='ZakazHim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('kol', models.FloatField(default=0, null=True, verbose_name='Количество')),
                ('cost', models.IntegerField(default=0, null=True, verbose_name='Цена')),
                ('creator', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Создатель')),
                ('time_create', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата/время создания')),
                ('maker', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Исполнитель')),
                ('time_make', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время выполнения')),
                ('deliver', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Доставил')),
                ('time_deliv', models.DateTimeField(blank=True, null=True, verbose_name='Дата/время доставления')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('ei_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ei', verbose_name='Ед.')),
                ('nomen_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.nomenhim', verbose_name='Химия')),
                ('receiver_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект')),
                ('source_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.source', verbose_name='База/Магазин')),
            ],
            options={
                'verbose_name': 'Заявка на химию',
                'verbose_name_plural': 'Заявки на химию',
            },
        ),
    ]
