# Generated by Django 4.2.13 on 2024-12-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_nomenhim_zakazremarkhim_alter_graphic_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vidopl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, null=True, verbose_name='Вид оплаты')),
            ],
            options={
                'verbose_name': 'Вид оплаты',
                'verbose_name_plural': 'Виды оплаты',
            },
        ),
        migrations.RemoveField(
            model_name='banket',
            name='avtor',
        ),
        migrations.RemoveField(
            model_name='banket',
            name='sbor',
        ),
        migrations.AddField(
            model_name='banket',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='banket',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='catalog.sotr', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='banket',
            name='contact',
            field=models.CharField(max_length=50, null=True, verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='banket',
            name='customer',
            field=models.CharField(max_length=50, null=True, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='banket',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект'),
        ),
        migrations.AddField(
            model_name='banket',
            name='predoplata',
            field=models.IntegerField(default=0, null=True, verbose_name='Предоплата'),
        ),
        migrations.AddField(
            model_name='banket',
            name='psbor',
            field=models.CharField(max_length=50, null=True, verbose_name='ПСбор'),
        ),
        migrations.AddField(
            model_name='banket',
            name='ssbor',
            field=models.IntegerField(default=0, null=True, verbose_name='С.Сбор'),
        ),
        migrations.AlterField(
            model_name='banket',
            name='kolg',
            field=models.IntegerField(default=0, null=True, verbose_name='Кол.гостей'),
        ),
        migrations.AlterField(
            model_name='banket',
            name='remark',
            field=models.TextField(default='', max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='banket',
            name='sum',
            field=models.IntegerField(default=0, null=True, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='banket',
            name='vidopl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opl', to='catalog.vidopl', verbose_name='Вид оплаты.'),
        ),
        migrations.AddField(
            model_name='banket',
            name='vidoplp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oplp', to='catalog.vidopl', verbose_name='Вид оплаты предоплата'),
        ),
    ]
