# Generated by Django 4.2.13 on 2025-02-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_receiver_img_stoplist_ost_alter_stoplist_autor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receiver',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объект'},
        ),
        migrations.AddField(
            model_name='den',
            name='alkk',
            field=models.FloatField(default=0, null=True, verbose_name='Алкоголь, Кол'),
        ),
        migrations.AddField(
            model_name='den',
            name='alkv',
            field=models.FloatField(default=0, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AddField(
            model_name='den',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Создал', to='catalog.sotr', verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='den',
            name='desk',
            field=models.FloatField(default=0, null=True, verbose_name='Дессерт, Кол'),
        ),
        migrations.AddField(
            model_name='den',
            name='desv',
            field=models.FloatField(default=0, null=True, verbose_name='Дессерт'),
        ),
        migrations.AddField(
            model_name='den',
            name='gork',
            field=models.FloatField(default=0, null=True, verbose_name='Горячее, Кол'),
        ),
        migrations.AddField(
            model_name='den',
            name='gorv',
            field=models.FloatField(default=0, null=True, verbose_name='Горячее'),
        ),
        migrations.AddField(
            model_name='den',
            name='holk',
            field=models.FloatField(default=0, null=True, verbose_name='Холодное, Кол'),
        ),
        migrations.AddField(
            model_name='den',
            name='holv',
            field=models.FloatField(default=0, null=True, verbose_name='Холодное'),
        ),
        migrations.AddField(
            model_name='den',
            name='kofk',
            field=models.FloatField(default=0, null=True, verbose_name='Кофе/Чай, Кол'),
        ),
        migrations.AddField(
            model_name='den',
            name='kofv',
            field=models.FloatField(default=0, null=True, verbose_name='Кофе/Чай'),
        ),
        migrations.AddField(
            model_name='den',
            name='pizk',
            field=models.FloatField(default=0, null=True, verbose_name='Пицца, Кол'),
        ),
        migrations.AddField(
            model_name='den',
            name='pizv',
            field=models.FloatField(default=0, null=True, verbose_name='Пицца'),
        ),
        migrations.AddField(
            model_name='receiver',
            name='k',
            field=models.IntegerField(blank=True, null=True, verbose_name='Коэффициент'),
        ),
        migrations.AddField(
            model_name='sotr',
            name='img',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='static/IMG', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Оъект'),
        ),
        migrations.CreateModel(
            name='VisitControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_in', models.DateTimeField(verbose_name='Дата приход')),
                ('dt_out', models.DateTimeField(verbose_name='Дата уход')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.podrazd', verbose_name='Подразделение')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект')),
                ('sotr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.sotr', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Учет посещений сотрудников',
                'verbose_name_plural': 'Учет посещений сотрудников',
            },
        ),
    ]
