# Generated by Django 4.2.13 on 2025-02-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_receiver_options_den_alkk_den_alkv_den_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='STask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Описание задачи')),
                ('date', models.DateTimeField(verbose_name='Дата/Время постановки')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/photo/%Y-%m-%d/', verbose_name='Image')),
                ('dateexecution', models.DateField(verbose_name='Дата исполнения')),
                ('daterenewal', models.DateField(verbose_name='Дата продления')),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.sotr', verbose_name='Создатель')),
                ('div', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.podrazd', verbose_name='Подразделение')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor01', to='catalog.sotr', verbose_name='Исполнитель')),
                ('executorpassed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor02', to='catalog.sotr', verbose_name='Передано Исполнителю')),
                ('obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.receiver', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи сотрудников',
            },
        ),
        migrations.CreateModel(
            name='STaskPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты задач',
            },
        ),
        migrations.CreateModel(
            name='STaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы задач',
            },
        ),
        migrations.CreateModel(
            name='STaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы задач',
            },
        ),
        migrations.CreateModel(
            name='STaskExe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Выполнение')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата/Время выполнения')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='static/photo/%Y-%m-%d/', verbose_name='Image')),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='catalog.sotr', verbose_name='Исполнитель')),
                ('executorpassed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor1', to='catalog.sotr', verbose_name='Передано Исполнителю')),
                ('priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.staskpriority', verbose_name='Приоритет')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.staskstatus', verbose_name='Статус')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.stask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Выполнение задачи',
                'verbose_name_plural': 'Выполнение задач',
            },
        ),
        migrations.AddField(
            model_name='stask',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.staskpriority', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='stask',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.staskstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='stask',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.stasktype', verbose_name='Тип'),
        ),
    ]
