# Generated by Django 4.2.20 on 2025-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_stask_staskpriority_staskstatus_stasktype_staskexe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stask',
            name='dateexecution',
            field=models.DateField(null=True, verbose_name='Дата исполнения'),
        ),
        migrations.AlterField(
            model_name='stask',
            name='daterenewal',
            field=models.DateField(null=True, verbose_name='Дата продления'),
        ),
    ]
