# Generated by Django 4.2.20 on 2025-04-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_stask_dateexecution_alter_stask_daterenewal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpimetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Описание метрики')),
                ('kol', models.IntegerField(default=0, null=True, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Метрика KPI',
                'verbose_name_plural': 'Метрика KPI',
            },
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата/Время постановки')),
                ('kol', models.IntegerField(default=0, null=True, verbose_name='Вес')),
                ('active', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sotr00', to='catalog.sotr', verbose_name='Автор')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.kpimetric', verbose_name='Метрика KPI')),
                ('sotr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sotr01', to='catalog.sotr', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Метрика KPI',
                'verbose_name_plural': 'Метрика KPI',
            },
        ),
    ]
